name: Internal to Release PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  sync_release_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "bot"
          git config user.email "bot@test.com"

      - name: Merge main into release/4x
        run: |
          git fetch origin release/4x
          git checkout release/4x
          git merge origin/main --no-ff -m "Sync main into release/4x [skip ci]"
          git push origin release/4x

      - name: Create PR to prod-release/public
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: prod-release/public
          branch: release/4x
          title: "Sync release/4x into prod-release/public"
          body: "Automated PR: Sync changes from internal repo main branch"
          update-branch: true