name: Internal to Release PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  sync_release_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "bot"
          git config user.email "bot@test.com"

      - name: Merge main into release/4x
        run: |
          git fetch origin
          git checkout origin/release/4x -B release/4x
          git merge origin/main --no-ff -m "Sync main into release/4x [skip ci]"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git release/4x