name: Sync to Public Repo

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - prod-release/public
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "sync-bot"
          git config --global user.email "sync-bot@example.com"

      - name: Add public repo as remote
        run: |
          git remote add public https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/varuncoderise/demo-public.git
          git fetch public

      - name: Push changes to public repo develop branch
        run: |
          git push public HEAD:develop --force
