name: Trigger Private Repo Sync

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger public repo workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }} 
          repository: varuncoderise/demo-private
          event-type: sync-request
          client-payload: '{"source_repo": "${{ github.repository }}", "source_ref": "main"}'